[package]
name = "rizon"
version = "0.1.0"
edition = "2021"

[dependencies]
rizon-frontend = { workspace = true }
rizon-runtime = { workspace = true }
rizon-static-analyzer = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
